# Generated by Django 4.2.6 on 2023-11-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_current_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='guest_can_add_song',
            field=models.BooleanField(default=False),
        ),
    ]
